### PR TITLE
Added functionality to scroll the page when dragging.

### PR DESCRIPTION
**Pull request by jamesbrauman**
Hi,

I needed a way to scroll the viewport when dragging an element to the edge of it as per issue fatlinesofcode/ngDraggable#71. I have added a new directive called **ngDragScroll** that accomplishes this. It has the following options you can configure:

| Option | What It Does |
| --- | --- |
| verticalScroll | Whether the viewport should scroll vertically. |
| horizontalScroll | Whether the viewport should scroll horizontally. |
| activationDistance | The distance from the edge of the viewport that scrolling should be activated. |
| scrollDistance | The distance to scroll (in pixels) per interval. |
| scrollInterval | The time between scrolls (in milliseconds). |

I had to implement a kind of hacky solution where I measured how much the page actually scrolled by removing the transform, scrolling and measuring, then reapplying the transform. Please let me know what you think or if you have any other ideas.

### CODE REVIEW

**Comment by Gunbit** [comment]
+1

**Comment by fatlinesofcode** [comment]
Merging this now, is there an example implementation?

**Comment by JamesBrauman** [comment]
@fatlinesofcode I'm using it in my code like this:

```
<div ng-drag="callback" ng-drag-scroll horizontalScroll="false"></div>
```

You can just use ng-drag-scroll by itself if you want to use the default settings.

**Comment by IrimieAndrei** [comment]
If you start dragging the element and then you start scrolling while you hold the dragged element, the issue remains. Am I missing something?

**Comment by ElTimuro** [comment]
+1

**Comment by Bhupesh82** [comment]
facing same issue (If you start dragging the element and then you start scrolling while you hold the dragged element, the issue remains. Am I missing something?) Could you please advise if we have found any solution for this?

**Pull request merged**
