### PR TITLE
Adding start and move events

### PR DESCRIPTION
**Pull request by bobber205**
Needed this for a project I was working on and thought I'd add it to the main code base. :)
Edit: Also added a dragging stopped general event.

### CODE REVIEW

**Comment by bobber205** [comment]
Any updates on this? I'd like to merge this in if possible. :)

**Comment by jkarttunen** [comment]
"This pull request contains merge conflicts that must be resolved." says github.

**Comment by bobber205** [comment]
Rebased with master. Sorry for the delay (work has been hectic lately). Hope to see this in master soon. :D

**Comment by jkarttunen** [comment]
Thanks :)

**Pull request merged**
